### ISSUE TITLE
Feature Request: Silent mode

### ISSUE THREAD

**Issue by mark-hallman** [AndrewRathbun/KAPE-EZToolsAncillaryUpdater#1]
Andrew,  as always, great work and a great tool.  I have been using it a lot.  

One of the uses is including it in my Packer scripts for building Forensic VMs.  After installing KAPE ,  I run your script just to make sure everything is up to date.  

It would be nice to be able to make it run in quite mode, like setting `$ProgressPreference = 'SilentlyContinue'` .  The script will run faster too.  I wondering how big of a deal it would to have a q**uite mode switch**?  That mode would also need to bypass the "pause" at the end.

I have made some crude changes on a local copy to see how this would work but I would prefer to grab a fresh copy of your script each time I start a build.

Thoughts?

Cheers,  Mark

**Comment by AndrewRathbun** [comment]
Hey thanks for the feedback! I'm really happy to hear you're getting good use out of it. If you want to do a PR with your changes I'd be happy to merge and I'll get the script signed for a new release! 

Either that or post your crude changes here and I can release a new signed version.

**Comment by AndrewRathbun** [comment]
I'm getting better at PowerShell so I'll include this in my rewrite that I'm working on now that there's multiple instances of EZ Tools now. I'll add this as a switch parameter so you can tack it on when you run it for your use case.

**Comment by AndrewRathbun** [comment]
@mark-hallman I'm about to update the script. Once you download that one and toy around with it, would you mind informing me how you best feel it should be implemented? The script has changed a lot since the version this Issue was made for, so it would warrant a new conversation once you see the new script.

**Comment by AndrewRathbun** [comment]
> @mark-hallman I'm about to update the script. Once you download that one and toy around with it, would you mind informing me how you best feel it should be implemented? The script has changed a lot since the version this Issue was made for, so it would warrant a new conversation once you see the new script. 

@mark-hallman https://github.com/AndrewRathbun/KAPE-EZToolsAncillaryUpdater/releases/tag/3.0 FYI

**Comment by andersnese** [comment]
I have the same use case as @mark-hallman described.
I created a PR for it here: https://github.com/AndrewRathbun/KAPE-EZToolsAncillaryUpdater/pull/6
