### ISSUE TITLE
clean up .net 4 functions

### ISSUE THREAD

**Issue by Donovoi** [AndrewRathbun/KAPE-EZToolsAncillaryUpdater#12]
.net 4 functions could be a lot cleaner, similar to the .net 6 ones. I'd like to make them a bit shorter and see where .net 4 and .net 6 can share some code instead of it being a copy paste job. 

Let me know if you are happy for me to work on this one.

**Comment by AndrewRathbun** [comment]
Go crazy with it! Thank you for your work. Really appreciated!

**Comment by AndrewRathbun** [comment]
> WOW! Thanks Andrew!! what an honour :D
> 
> More to come!

Good work should be recognized. Thanks for all you do!

**Comment by AndrewRathbun** [comment]
.NET 6 is the default now, as discussed in https://github.com/AndrewRathbun/KAPE-EZToolsAncillaryUpdater/issues/16. There's no need to do this anymore.
