### ISSUE TITLE
Question - Why are you forcing the download / reinstall of Zimmerman Tools

### ISSUE THREAD

**Issue by mark-hallman** [AndrewRathbun/KAPE-EZToolsAncillaryUpdater#20]
The current version (4.1) of KAPE-EZToolsAncillaryUpdater.ps1 is forcing the download and reinstall of ZimmermanTools each time the the script is run. I understand that on the initial run of KAPE-EZToolsAncillaryUpdater.ps1 that is is a good idea,  but each run after that should rely on Get-ZimmermanTools to determine if there are newer versions of any of the ZimmermanTools that need to be downloaded and installed.  

Think of it this way.  1st run of KAPE-EZToolsAncillaryUpdater.ps1 needs to install new version of KAPE and ancillary tools as well as the latest version of the ZimmermanTools.  If you then immediately run the KAPE-EZToolsAncillaryUpdater.ps1 script again,  there should be no updates and it run in seconds.  

It looks like the same thing is happening for event log maps, recmd batch examples, and sqlecmd maps.

This is probably more of a performance fine tuning than anything. It is not a bug.  The script works, but in terms of a percentage of run time, it takes a lot longer than it should.  Looking at it from a user POV, it only takes about 1:15 to run.  That time could probably be cut down to 15 sec for a system that is mostly up to  date.

**Comment by AndrewRathbun** [comment]
Talked with Mark on the phone about this, closing the issue for now!
