### ISSUE TITLE
Additional switch request

### ISSUE THREAD

**Issue by opcilantr0** [AndrewRathbun/KAPE-EZToolsAncillaryUpdater#22]
**Script Info**

From your KAPEUpdate.log file, please paste the first few lines that display the script name, hash, etc. For example:  
  
```  
[2023-06-13 22:23:13] | Script Name: KAPE-EZToolsAncillaryUpdater.ps1
[2023-06-13 22:23:13] | Full Path: D:\KAPE-EZToolsAncillaryUpdater\KAPE-EZToolsAncillaryUpdater.ps1
[2023-06-13 22:23:13] | Last Modified Date: 06/13/2023 22:23:07
[2023-06-13 22:23:13] | File Size: 43655 bytes | 0.04 MB
[2023-06-13 22:23:13] | Certificate Expiration: 01/26/2025 18:59:59
[2023-06-13 22:23:13] | MD5 Hash: A9E7D1DB7A8C41B9424DEC57297CC9E6
```

Feel free to edit out any sensitive file paths, if needed.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

As discussed in Discord channel, it would be good if I could have a switch for the script to only pull down updated files only.

Let me know if you need more details.

**Comment by AndrewRathbun** [comment]
@opcilantr0 give this a try: `KAPE-EZToolsAncillaryUpdater.ps1 -KeepEZTools` will NOT delete the `!!!RemoteFileDetails.csv` file which `Get-ZimmermanTools.ps1` relies on to figure out what's on disk vs what's hosted on Backblaze. Try it without that switch too, and ensure everything is working as you expected.

Also, make sure I didn't get it backwards, or if you have a better name for that switch, let me know and I'll make the change before pushing out a new release.

Cheers, and thanks for the feature request!

[KAPE-EZToolsAncillaryUpdater.zip](https://github.com/AndrewRathbun/KAPE-EZToolsAncillaryUpdater/files/12876703/KAPE-EZToolsAncillaryUpdater.zip)

GitHub doesn't allow PS1 files so I had to ZIP it up.
